# Generated by Django 3.2.13 on 2023-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
