# Generated by Django 3.2.13 on 2023-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
