# Generated by Django 3.2.13 on 2023-03-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=55)),
                ('image', models.CharField(max_length=55)),
                ('genre', models.CharField(max_length=55)),
                ('content_en', models.TextField(max_length=2047)),
                ('content_ko', models.TextField(max_length=2047)),
                ('voice', models.CharField(max_length=55)),
            ],
        ),
    ]
